use crate::utils::{
    constants::{EMPTY_TREE_VALUE, FR_ZERO, MERKLE_TREE_DEPTH},
    errors::DappError,
    poseidon_hash,
    flatten_array::{get_array_element, set_array_element},
};
use quasar_lang::prelude::*;
// QuasarSerialize expands to bare `zeropod::` / `solana_program_error::` paths.
// Quasar only re-exports them as `__zeropod` / `__solana_program_error`, so alias
// to the names the macro expects.
use quasar_lang::{__solana_program_error as solana_program_error, __zeropod as zeropod};

/// Incremental Merkle Tree state for inserted deposit commitments.
///
/// # Fields
///
/// - `root` - current root of the tree (root level == MERKLE_TREE_DEPTH, leaf level == 0)
///
/// - `frontiers` - also called filledSubtrees. It stores exactly one hash per level — the hash of the
///   most recently updated left subtree at that level.
///   One value per level (no need to store it for root level)
///
/// - `zero_values` - Z_k for each level k (precomputed). Contains MERKLE_TREE_DEPTH values (we do not need it on root level)
///
/// - `next_leaf_idx` - Index of the next leaf to be inserted (0.. 2^MERKLE_TREE_DEPTH)
///   First (leaf) level depth == 0 and amount of leafs at this level is 2^MERKLE_TREE_DEPTH
///
/// @dev Note:
/// frontiers and zero_values store 32-byte scalar field elements in little endian format.
/// Normally each would be its own `[u8; 32]`, giving a declaration like:
///   frontiers: [[u8; 32]; MERKLE_TREE_DEPTH]
/// but zeropod only implements its field traits for byte arrays, so the levels are
/// flattened and indexed by hand through [`get_array_element`] / [`set_array_element`]:
///   frontiers: [u8; 32 * MERKLE_TREE_DEPTH] // MERKLE_TREE_DEPTH levels of 32 bytes each
//
// QuasarSerialize is what lets this struct nest inside a `#[account]` struct: it supplies the
// `ZcField` mapping the account macro looks for, the `InstructionArg` conversion `set_inner`
// calls, and the IDL type definition the generated clients resolve. It also publishes the
// zero-copy companion `ImtTreeZc` - that is the type an account actually holds, so the
// mutating methods live on it rather than on `ImtTree`.
#[derive(QuasarSerialize, Clone, Copy)]
pub struct ImtTree {
    pub root: [u8; 32],
    pub frontiers: [u8; 32 * MERKLE_TREE_DEPTH],
    pub zero_values: [u8; 32 * MERKLE_TREE_DEPTH],
    pub next_leaf_idx: u32,
}

impl ImtTree {
    /// An empty tree: no leaves inserted, but still a well-formed Merkle tree with zero values as leaves.
    /// Used for off-chain tests for IMT properties and in Quasar tests.
    pub fn new() -> Result<Self, ProgramError> {
        let mut frontiers = [0u8; 32 * MERKLE_TREE_DEPTH];
        let mut zero_values = [0u8; 32 * MERKLE_TREE_DEPTH];
        let root = initialize_empty_tree_arrays(&mut frontiers, &mut zero_values)?;

        Ok(Self {
            root,
            frontiers,
            zero_values,
            next_leaf_idx: 0,
        })
    }
}

/// ImtTreeZc is the zero-copy companion generated by QuasarSerialize. Native scalars become Pod types (e.g. u32 → PodU32) so the 
/// layout is alignment-1 and safe to borrow from account bytes; byte arrays stay unchanged. 
/// Mutating methods live here because a loaded RootRegistry exposes imt as ImtTreeZc converting from ImtTree to mutate 
/// would copy the whole tree. Unlike #[account] types (methods on RootRegistry, which Deref to the zero-copy data),
/// nested QuasarSerialize types have no Deref wrapper, so logic that mutates account-backed state goes on *Zc.
impl ImtTreeZc {

    /// Initialize frontiers and zero_values to empty tree values in place (with not stack/heap allocations)
    pub fn initialize_empty(&mut self) -> Result<(), ProgramError> {
        // We are passing frontiers and zero_values which are on already on-chain as part of RootRegistry account data
        // (after handler is called this space is already given to us but may not be emptied)
        self.root = initialize_empty_tree_arrays(&mut self.frontiers, &mut self.zero_values)?;
        self.next_leaf_idx = PodU32::from(0);

        Ok(())
    }

    /**
     * Example tree indexes for depth = 3 (note: we use level-local indexing - each level index starts from 0) :
     *                     R_0                   - level 3 (root)
     *           A_0                A_1          - level 2
     *     B_0      B_1        B_2         B_3   - level 1
     *  C_0  C_1  C_2  C_3  C_4  C_5  C_6  C_7   - level 0 (leafs)
     */
    pub fn insert(&mut self, leaf: [u8; 32]) -> Result<[u8; 32], ProgramError> {
        let next_leaf_idx = self.next_leaf_idx.get();
        if next_leaf_idx as usize >= 1usize << MERKLE_TREE_DEPTH {
            return Err(DappError::TreeIsFull.into());
        }

        // traverse tree from leaf to root (current leaf index on leaf level == next_leaf_index)
        // each level node indexing starts from 0
        let mut current_idx = next_leaf_idx;
        let mut current_node_value = leaf;
        for current_level in 0..MERKLE_TREE_DEPTH {
            let is_left_leaf = current_idx % 2 == 0;

            // go level up add calculate upper node value
            if is_left_leaf {
                set_array_element(&mut self.frontiers, current_level, &current_node_value);
                current_node_value =
                    poseidon_hash::hash2(current_node_value, self.zero_value(current_level))?
            } else {
                current_node_value =
                    poseidon_hash::hash2(self.frontier(current_level), current_node_value)?
            };
            current_idx /= 2;
        }

        self.root = current_node_value;
        self.inc_next_leaf_idx();

        Ok(current_node_value)
    }

    fn inc_next_leaf_idx(&mut self) {
        self.next_leaf_idx += 1;
    }

    pub fn frontier(&self, level: usize) -> [u8; 32] {
        get_array_element(&self.frontiers, level)
    }

    pub fn zero_value(&self, level: usize) -> [u8; 32] {
        get_array_element(&self.zero_values, level)
    }
}

/// In place initialization of frontiers and zero_values with not stack/heap allocations
fn initialize_empty_tree_arrays(
    frontiers: &mut [u8; 32 * MERKLE_TREE_DEPTH],
    zero_values: &mut [u8; 32 * MERKLE_TREE_DEPTH],
) -> Result<[u8; 32], ProgramError> {
    set_array_element(zero_values, 0, &FR_ZERO);

    // generate zero_values for all tree levels (except root level)
    for level in 1..MERKLE_TREE_DEPTH {
        let previous_zero_value = get_array_element(zero_values, level - 1);
        let zero_value = poseidon_hash::hash2(previous_zero_value, previous_zero_value)?;
        set_array_element(zero_values, level, &zero_value);
    }

    // set frontiers to empty values
    for level in 0..MERKLE_TREE_DEPTH {
        set_array_element(frontiers, level, &EMPTY_TREE_VALUE);
    }

    let below_root_zero_value = get_array_element(zero_values, MERKLE_TREE_DEPTH - 1);
    let root = poseidon_hash::hash2(below_root_zero_value, below_root_zero_value)?;
    Ok(root)
}

#[cfg(test)]
mod tests {
    use super::*;
    // Ported from the circuit crate's `on_chain_imt` tests

    fn test_leaf(index: u64) -> [u8; 32] {
        let mut leaf = [0u8; 32];
        leaf[..8].copy_from_slice(&index.to_le_bytes());
        leaf
    }

    fn empty_tree() -> ImtTreeZc {
        ImtTree::new().unwrap().into()
    }

    #[test]
    fn new_tree_starts_empty_with_the_zero_value_root() {
        let imt = ImtTree::new().unwrap();

        assert_eq!(imt.next_leaf_idx, 0);

        // Z_0 is the field zero; every level above is the level below hashed with itself.
        assert_eq!(get_array_element(&imt.zero_values, 0), FR_ZERO);
        for level in 1..MERKLE_TREE_DEPTH {
            let below = get_array_element(&imt.zero_values, level - 1);
            assert_eq!(
                get_array_element(&imt.zero_values, level),
                poseidon_hash::hash2(below, below).unwrap(),
                "zero value at level {level} is not the level below hashed with itself"
            );
        }

        let top_zero_value = get_array_element(&imt.zero_values, MERKLE_TREE_DEPTH - 1);
        assert_eq!(
            imt.root,
            poseidon_hash::hash2(top_zero_value, top_zero_value).unwrap()
        );

        for level in 0..MERKLE_TREE_DEPTH {
            assert_eq!(get_array_element(&imt.frontiers, level), EMPTY_TREE_VALUE);
        }
    }

    #[test]
    fn insert_increments_next_leaf_idx() {
        let mut imt = empty_tree();
        assert_eq!(imt.next_leaf_idx.get(), 0);

        for i in 1..=8u64 {
            imt.insert(test_leaf(i)).unwrap();
            assert_eq!(imt.next_leaf_idx.get(), i as u32);
        }
    }

    #[test]
    fn insert_returns_a_new_root_every_time() {
        // Eight inserts walk both the left and the right branch at the three lowest levels.
        let mut imt = empty_tree();
        let mut seen_roots = std::vec![imt.root];

        for i in 1..=8u64 {
            let returned_root = imt.insert(test_leaf(i)).unwrap();
            assert_eq!(
                returned_root, imt.root,
                "insert returned a root that differs from the stored one after {i} inserts"
            );
            assert!(
                !seen_roots.contains(&returned_root),
                "root repeated after {i} inserts"
            );
            seen_roots.push(returned_root);
        }
    }

    #[test]
    fn first_insert_records_the_leaf_as_the_level_zero_frontier() {
        let mut imt = empty_tree();
        let leaf = test_leaf(42);

        imt.insert(leaf).unwrap();

        assert_eq!(imt.frontier(0), leaf);
    }

    #[test]
    fn insert_fills_the_last_slot_then_rejects_a_full_tree() {
        const CAPACITY: u32 = 1 << MERKLE_TREE_DEPTH;

        let mut imt = empty_tree();

        // Inside the boundary: the last free slot still takes a leaf. This index is all
        // ones, so it also exercises the right-hand branch at every level.
        imt.next_leaf_idx = PodU32::from(CAPACITY - 1);
        imt.insert(test_leaf(1)).unwrap();
        assert_eq!(imt.next_leaf_idx.get(), CAPACITY);

        // Outside the boundary: rejected, and the tree is left untouched.
        let root_before = imt.root;
        let frontiers_before = imt.frontiers;
        assert!(imt.insert(test_leaf(2)).is_err());
        assert_eq!(imt.root, root_before);
        assert_eq!(imt.frontiers, frontiers_before);
        assert_eq!(imt.next_leaf_idx.get(), CAPACITY);
    }

    #[test]
    fn same_leaves_produce_the_same_root() {
        let mut imt_a = empty_tree();
        let mut imt_b = empty_tree();

        for i in 1..=6u64 {
            imt_a.insert(test_leaf(i)).unwrap();
            imt_b.insert(test_leaf(i)).unwrap();
        }

        assert_eq!(imt_a.root, imt_b.root);
    }
}
